spring:

  application:
    name: Expense-Tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker
    username: postgres
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-table: exp_changelog
    database-change-log-lock-table: exp_changelog_lock
    contexts: dev

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    user:
      name: avs
      password: pass

jwt:
  secretKey: jnjewhf9823njwenjker23jkj23423n2312fsrewfwede

deploy:
  env: dev
